# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {F:/Dropbox/ece532_fpga Team Folder/new_color_ip/ip_repo/edit_color_mk2_v1_0.cache/wt} [current_project]
set_property parent.project_path {F:/Dropbox/ece532_fpga Team Folder/new_color_ip/ip_repo/edit_color_mk2_v1_0.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{f:/Dropbox/ece532_fpga Team Folder/new_color_ip/ip_repo/color_mk2_1.0}} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  {F:/Dropbox/ece532_fpga Team Folder/new_color_ip/ip_repo/color_mk2_1.0/hdl/color_mk2_v1_0_M00_AXIS.v}
  {F:/Dropbox/ece532_fpga Team Folder/new_color_ip/ip_repo/color_mk2_1.0/hdl/color_mk2_v1_0_S00_AXIS.v}
  {F:/Dropbox/ece532_fpga Team Folder/new_color_ip/ip_repo/color_mk2_1.0/hdl/color_mk2_v1_0.v}
}
synth_design -top color_mk2_v1_0 -part xc7a200tsbg484-1
write_checkpoint -noxdef color_mk2_v1_0.dcp
catch { report_utilization -file color_mk2_v1_0_utilization_synth.rpt -pb color_mk2_v1_0_utilization_synth.pb }
